### ISSUE TITLE
Re-enable image builds

### ISSUE THREAD

**Issue by jauderho** [pi-hole/docker-base-images#35]
### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  

- Platform:  

### Expected behavior

Regular image builds

### Actual behavior / bug

It looks like images stopped building 2 months ago. This can be verified by looking at Docker Hub pi-hole base images

https://hub.docker.com/r/pihole/debian-base/tags?page=1&ordering=last_updated

### Steps to reproduce

1. Go to https://github.com/pi-hole/docker-base-images/actions
2. Re-enable workflow
3. Trigger new docker image build
4. Probably a good idea to bump the whole pipeline as that's 2 months of missing fixes.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
👍 Have reenabled it, I guess easiest is to wait til Sunday @2am for it to trigger again

**Comment by jauderho** [comment]
If you add a workflow_dispatch trigger, you can manually trigger an action at any time.

See https://github.com/jauderho/dockerfiles/blob/2cc45b4481d9a022cf11616edfd3c73415912758/.github/workflows/ansible.yml#L10  for an example.

Do you want me to create a pull request?

**Comment by PromoFaux** [comment]
Yep, familiar with those 🙂 

See:
https://github.com/pi-hole/docker-pi-hole/blob/master/.github/workflows/workflow_dispatch.yml

But sure, please do!

**Comment by jauderho** [comment]
Done #36

**Comment by jauderho** [comment]
Looks like Docker Hub was updated. I would suggest pushing a new Pi-hole build just to pick up the new base images.

On a related note, is there a reason why the x86 build does not use the -slim Debian image?

**Comment by PromoFaux** [comment]
> On a related note, is there a reason why the x86 build does not use the -slim Debian image?

Sorry for the long delay in reply, actually all arch's use `buster-slim` these days, as we have switched to using `buildx`, and no longer needed special base images we had in this repo.
