### ISSUE TITLE
Enable `lighttpd-mod-ssl` on debian:bullseye image

### ISSUE THREAD

**Issue by rdwebdesign** [pi-hole/docker-base-images#48]
I don't know if this is still necessary, but I created this issue as a reminder based on comment below:

> I wonder if this should, instead, go into the base image? https://github.com/pi-hole/docker-base-images

_Originally posted by @PromoFaux in https://github.com/pi-hole/docker-pi-hole/issues/1009#issuecomment-1053626664_

**Comment by rdwebdesign** [comment]
@PromoFaux 

I created this reminder after PR 1009, but after that, you reverted that changes in PR #1028. You also [commented about this here](https://github.com/pi-hole/docker-pi-hole/issues/1046#issuecomment-1086647545).

Do you think we should enable this on the base image?
Is there something we need to change after all `lighttpd` recent changes?
or should we close this issue?

**Comment by MichaIng** [comment]
Done already: https://github.com/pi-hole/docker-base-images/commit/4051456
The module is enabled automatically on install.
